- hosts: kubernetes-worker-nodes
  become: yes
  become_user: root
  vars_files:
    - env_variables
  tasks:
    - name: Copy token to worker nodes
      copy:
        src: "{{ token_file }}"
        dest: join_token
        mode: '0777'
    - name: Read Script File
      slurp:
        src: /home/azureuser/join_token
      register: script_content

    - name: Extract Join Command and Token
      set_fact:
        join_command: "{{ script_content.content | regex_search('kubeadm join manager:6443.*') }}"
        join_token: "{{ join_command | regex_search('--token ([^[:space:]]+)') }}"
      
    - name: Execute Join Command
      shell: "{{ join_command }}"

